Remove defining 'const' as nothing
This is a hack to override constness of struct members
however, with modern compiler like clang with fortified
glibc ( 2.40+ ) headers this runs into compiler errors

| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/flite/2.2/recipe-sysroot/usr/include/bits/stdlib.h:38:54: error: pass_object_size attribute only applies to constant pointer arguments
|    38 |                  __fortify_clang_overload_arg (char *, __restrict, __resolved)))
|       |                                                                    ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/flite/2.2/recipe-sysroot/usr/include/bits/stdlib.h:73:43: error: pass_object_size attribute only applies to constant pointer arguments
|    73 |                  __fortify_clang_overload_arg (char *, ,__buf),
|       |                                                         ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/flite/2.2/recipe-sysroot/usr/include/bits/stdlib.h:91:55: error: pass_object_size attribute only applies to constant pointer arguments
|    91 | __NTH (wctomb (__fortify_clang_overload_arg (char *, ,__s), wchar_t __wchar))
|       |                                                       ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/flite/2.2/recipe-sysroot/usr/include/bits/stdlib.h:129:71: error: pass_object_size attribute only applies to constant pointer arguments
|   129 | __NTH (mbstowcs (__fortify_clang_overload_arg (wchar_t *, __restrict, __dst),
|       |                                                                       ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/flite/2.2/recipe-sysroot/usr/include/bits/stdlib.h:159:68: error: pass_object_size attribute only applies to constant pointer arguments
|   159 | __NTH (wcstombs (__fortify_clang_overload_arg (char *, __restrict, __dst),
|       |                                                                    ^
| 5 errors generated.
|

Therefore take this out, instead cast away the 'const' qualifier where needed ( equilly dangerous )
however limited to just this file instead of apply to all headers including system headers

Signed-off-by: Khem Raj <raj.khem@gmail.com>